UNIT ARCHIVOEVAL;
{$CODEPAGE UTF8}

INTERFACE

USES
  CRT;

CONST
    RUTA = 'C:\TPFinal\TPFINAL2\TrabajoFinalAlgoritmos.DAT';

TYPE
  T_FECHA = RECORD
    DIA:1..31;
    MES:1..12;
    ANIO:WORD;
  END;

  T_DATO_EVAL = RECORD
    NUM_LEGAJO:STRING[8];
    FECHA_EVAL:T_FECHA;
    VALORACION: ARRAY [1..5] OF INTEGER;
    OBS:STRING[255];
  END;

  T_ARCHIVO_EVAL = FILE OF T_DATO_EVAL;

PROCEDURE CREAR_ABRIR2 (VAR ARCH:T_ARCHIVO_EVAL);
PROCEDURE CERRAR2 (VAR ARCH:T_ARCHIVO_EVAL);

IMPLEMENTATION

PROCEDURE CREAR_ABRIR2 (VAR ARCH:T_ARCHIVO_EVAL);
BEGIN
    ASSIGN(ARCH, RUTA);
    {$I-}
    RESET(ARCH);
    {$I+}
    IF IORESULT<>0 THEN
        REWRITE(ARCH);
END;

PROCEDURE CERRAR2 (VAR ARCH:T_ARCHIVO_EVAL);
BEGIN
    CLOSE(ARCH);
END;
END.