UNIT MANEJOEVAL;

{$CODEPAGE UTF8}

INTERFACE

USES
    CRT, ARCHIVOEVAL, UNITARBOL, SYSUTILS, VALIDACIONES, ARCHIVOALUM, ESTADISTICAS ;

PROCEDURE CARGARDATOSEVAL (VAR X:T_DATO_EVAL; VAR ARCHIVOALUMNO:T_ARCHIVO_ALUMNOS; VAR ARCHIVOEVAL:T_ARCHIVO_EVAL; POS:INTEGER);
PROCEDURE PASAR_DATOS_EVAL (VAR ARCH: T_ARCHIVO_EVAL; VAR RAIZLEGAJO,RAIZFECHA:T_PUNT_ARBOL);
PROCEDURE DARALTAEVAL (VAR ARCHIVOEVAL:T_ARCHIVO_EVAL; VAR X:T_DATO_EVAL; VAR ARCHIVOALUMNO:T_ARCHIVO_ALUMNOS; POS:INTEGER);
PROCEDURE CARGARALTAEVAL (VAR ARCHIVOEVAL:T_ARCHIVO_EVAL; VAR X:T_DATO_EVAL);
PROCEDURE MUESTRADATOSEVAL(X:T_DATO_EVAL);
PROCEDURE CONSULTAEVALUACION(VAR RAIZLEGAJO: T_PUNT_ARBOL; VAR ARCHIVOEVAL: T_ARCHIVO_EVAL; VAR ARCHIVOALUMNO:T_ARCHIVO_ALUMNOS; POSALUMNO: INTEGER);
PROCEDURE MODIFICAREVAL(VAR RAIZAPYNOM, RAIZLEGAJO: T_PUNT_ARBOL; VAR ARCHIVOEVAL: T_ARCHIVO_EVAL; VAR ARCHIVOALUMNO:T_ARCHIVO_ALUMNOS; POSALUMNO:INTEGER);
FUNCTION BUSCAREVALUACION(VAR RAIZLEGAJO: T_PUNT_ARBOL; VAR ARCHIVOEVAL: T_ARCHIVO_EVAL; LEGAJO: STRING; FECHA: STRING): INTEGER;
PROCEDURE MUESTRA_REGISTRO_POR_TABLA_EVAL (VAR X: T_DATO_EVAL);

IMPLEMENTATION


PROCEDURE PASAR_DATOS_EVAL(VAR ARCH: T_ARCHIVO_EVAL; VAR RAIZLEGAJO, RAIZFECHA: T_PUNT_ARBOL);
VAR
  X: T_DATO_EVAL;
  I: BYTE;
  R: T_DATO_ARBOL;
  FECHA: STRING;
BEGIN
  I := 0;
  BEGIN
    WHILE (I < FILESIZE(ARCH)) AND NOT EOF(ARCH) DO
    BEGIN
      SEEK(ARCH, I);
      READ(ARCH, X);

      // VALIDAR LOS DATOS DE LA FECHA
      IF (VALIDARFECHAANIO(X.FECHA_EVAL.ANIO)) AND (VALIDARFECHADIAMES(X.FECHA_EVAL.MES)) AND (VALIDARFECHADIAMES(X.FECHA_EVAL.DIA)) THEN
      BEGIN
        FECHA := (X.FECHA_EVAL.ANIO) + (X.FECHA_EVAL.MES) + (X.FECHA_EVAL.DIA);
        R.CLAVE := FECHA;
        R.POSARCH := I;
        AGREGAR_ARBOL(RAIZFECHA, R);
      END
      ELSE
      BEGIN
        // WRITELN('FECHA INVÁLIDA EN EL REGISTRO: ', I);
      END;

      I := I + 1;
    END;
  END;
END;



PROCEDURE CARGARDATOSEVAL (VAR X:T_DATO_EVAL; VAR ARCHIVOALUMNO:T_ARCHIVO_ALUMNOS; VAR ARCHIVOEVAL:T_ARCHIVO_EVAL; POS:INTEGER);
VAR
   I:BYTE;
   FECHA,ENTRADA:STRING;
   VALORACION:STRING;
   Y:T_DATO_ALUMNOS;
   LEGAJO:STRING;
BEGIN
     CLRSCR;
     GOTOXY(50,2);
     WRITELN('**DAR ALTA EVALUACIÓN**');
     TEXTCOLOR(GREEN);
     GOTOXY(45,4);
      SEEK(ARCHIVOALUMNO, POS);
      READ(ARCHIVOALUMNO, Y);
     X.NUM_LEGAJO :=  Y.NUM_LEGAJO;
     REPEAT
     TEXTCOLOR(GREEN);
     GOTOXY(45,6);
     WRITE('INGRESE DIA DE EVALUACIÓN: ');
     TEXTCOLOR(WHITE);
     READLN(X.FECHA_EVAL.DIA);
     WHILE NOT VALIDARFECHADIAMES(X.FECHA_EVAL.DIA) DO
          BEGIN
         GOTOXY(45,2);
          TEXTCOLOR(RED);
          WRITELN('DIA INVALIDO, POR FAVOR VERIFIQUE E INGRESE NUEVAMENTE');
          TEXTCOLOR(GREEN);
          GOTOXY(45,6);
          WRITE('INGRESE DIA DE EVALUACIÓN: ');
          TEXTCOLOR(WHITE);
          READLN(X.FECHA_EVAL.DIA);
          GOTOXY(45,11);
          WRITELN('                                                                                             ');
          END;
     TEXTCOLOR(GREEN);
     GOTOXY(45,8);
     WRITE('INGRESE MES DE EVALUACIÓN: ');
     TEXTCOLOR(WHITE);
     READLN(X.FECHA_EVAL.MES);
      WHILE NOT VALIDARFECHADIAMES(X.FECHA_EVAL.MES) DO
          BEGIN
         GOTOXY(45,2);
          TEXTCOLOR(RED);
          WRITELN('MES INVALIDO, POR FAVOR VERIFIQUE E INGRESE NUEVAMENTE');
          TEXTCOLOR(GREEN);
          GOTOXY(45,8);
          WRITE('INGRESE MES DE EVALUACIÓN: ');
          TEXTCOLOR(WHITE);
          READLN(X.FECHA_EVAL.MES);
          GOTOXY(45,2);
          WRITELN('                                                                                             ');
          END;
     TEXTCOLOR(GREEN);
     GOTOXY(45,10);
     WRITE('INGRESE AÑO DE EVALUACIÓN: ');
     TEXTCOLOR(WHITE);
     READLN(X.FECHA_EVAL.ANIO);
     WHILE NOT (VALIDARFECHAANIO(X.FECHA_EVAL.ANIO)) DO
          BEGIN
         GOTOXY(45,2);
          TEXTCOLOR(RED);
          WRITELN('AÑO INVALIDO, POR FAVOR VERIFIQUE E INGRESE NUEVAMENTE');
          TEXTCOLOR(GREEN);
          GOTOXY(45,10);
          WRITE('INGRESE AÑO DE EVALUACIÓN: ');
          TEXTCOLOR(WHITE);
          READLN(X.FECHA_EVAL.ANIO);
          GOTOXY(45,2);
          WRITELN('                                                                                             ');
          END;
     FECHA:=(X.FECHA_EVAL.DIA) + ' / ' + (X.FECHA_EVAL.MES) + ' / ' + (X.FECHA_EVAL.ANIO);
           IF NOT ESFECHAVALIDA(FECHA) THEN
     BEGIN
       CLRSCR;
       TEXTCOLOR(RED);
       GOTOXY(30,15);
       WRITELN('FECHA INVALIDA. VUELVA A INGRESAR CORRECTAMENTE LOS DATOS');
       TEXTCOLOR(WHITE);
       GOTOXY(43,17);
       WRITELN('OPRIMA <<ENTER>> PARA RECARGAR');
       READKEY;
       CLRSCR;
     END
           ELSE
           BEGIN
           LEGAJO:=X.NUM_LEGAJO;
           IF FECHAEXISTENTE (ARCHIVOEVAL,FECHA,LEGAJO) THEN
              BEGIN
                CLRSCR;
                WRITELN('FECHA EXISTENTE. NO ES POSIBLE CARGAR MAS DE 1 EVALUACION POR DIA');
              END;
           END;
    UNTIL ESFECHAVALIDA(FECHA) AND NOT FECHAEXISTENTE (ARCHIVOEVAL,FECHA,LEGAJO);

GOTOXY(45,13);
WRITELN('INGRESE LAS VALORACIONES DE 1 A 4 ');
TEXTCOLOR(LIGHTGRAY);
GOTOXY(35,14);
WRITELN('A LAS DISCAPACIDADES QUE NO APLICAN SE LES ASIGNARÁ 0');
FOR I:= 1 TO 5 DO
BEGIN
    TEXTCOLOR(GREEN);
    GOTOXY(40,15);
    IF Y.DISCAPACIDAD[I] THEN
    BEGIN

         REPEAT
          GOTOXY(40,15+I);
          TEXTCOLOR(GREEN);
          WRITE('VALORACIÓN PARA ', OBTENERNOMBREDISCAPACIDAD(I), ' : ');
          TEXTCOLOR(WHITE);
          READLN(VALORACION);

          IF NOT ESNUMERO(VALORACION) OR (VALORACION = '') THEN
          BEGIN
            TEXTCOLOR(RED);
            GOTOXY(46,22);
            WRITE('ERROR: INGRESE UN NUMERO ENTRE 1 Y 4.');
            DELAY(1500);
            GOTOXY(46,22);
            CLREOL;
            GOTOXY(51,20);
            CLREOL;
          END
          ELSE
          BEGIN
            IF (VALORACION < '1') OR (VALORACION > '4') THEN
            BEGIN
              TEXTCOLOR(RED);
              GOTOXY(47,22);
              WRITE('ERROR: OPCION FUERA DE RANGO.');
              DELAY(2000);
              GOTOXY(47,22);
              CLREOL;
              GOTOXY(51,20);
              CLREOL;
            END;
          END;
        UNTIL  ESNUMERO(VALORACION) AND (VALORACION > '0') AND (VALORACION <= '4') AND (VALORACION <> '');

    END
    ELSE
    BEGIN
        VALORACION := '0';
    END;
    X.VALORACION[I] := STRTOINT(VALORACION);


END;
TEXTCOLOR(GREEN);
GOTOXY(2,22);
WRITE('OBSERVACIONES: ');
TEXTCOLOR(WHITE);
READLN(X.OBS);

END;

PROCEDURE MUESTRADATOSEVAL(X:T_DATO_EVAL);
BEGIN
    CLRSCR;
    GOTOXY(8,10);
    WRITELN('DATOS ACTUALES DE LA EVALUACION:');
    TEXTCOLOR(GREEN);
    GOTOXY(10,12);
    WRITE('LEGAJO: ');
    TEXTCOLOR(WHITE);
    WRITELN(X.NUM_LEGAJO);
    TEXTCOLOR(GREEN);
    GOTOXY(10,14);
    WRITE('FECHA: ');
    TEXTCOLOR(WHITE);
    WRITELN(X.FECHA_EVAL.DIA, '/', X.FECHA_EVAL.MES, '/', X.FECHA_EVAL.ANIO);
    TEXTCOLOR(GREEN);
    GOTOXY(10,16);
    WRITE('VALORACION: ');
    TEXTCOLOR(WHITE);
    WRITELN(X.VALORACION[1], ' ', X.VALORACION[2], ' ', X.VALORACION[3], ' ', X.VALORACION[4], ' ', X.VALORACION[5]);
    TEXTCOLOR(GREEN);
    GOTOXY(10,18);
    WRITE('OBSERVACIONES: ');
    TEXTCOLOR(WHITE);
    WRITELN(X.OBS);
END;

PROCEDURE CARGARALTAEVAL (VAR ARCHIVOEVAL:T_ARCHIVO_EVAL; VAR X:T_DATO_EVAL);
BEGIN
    SEEK(ARCHIVOEVAL, FILESIZE(ARCHIVOEVAL));
    WRITE(ARCHIVOEVAL, X);
END;

PROCEDURE DARALTAEVAL (VAR ARCHIVOEVAL:T_ARCHIVO_EVAL; VAR X:T_DATO_EVAL; VAR ARCHIVOALUMNO:T_ARCHIVO_ALUMNOS; POS:INTEGER);
VAR
    FINARCH:CARDINAL;
BEGIN
    CARGARDATOSEVAL(X,ARCHIVOALUMNO,ARCHIVOEVAL,POS);
    CARGARALTAEVAL(ARCHIVOEVAL, X);
END;

FUNCTION BUSCAREVALUACION(VAR RAIZLEGAJO: T_PUNT_ARBOL; VAR ARCHIVOEVAL: T_ARCHIVO_EVAL; LEGAJO: STRING; FECHA: STRING): INTEGER;
VAR
  POS,I: INTEGER;
  X: T_DATO_EVAL;
BEGIN
    BUSCAREVALUACION:=-1;
FOR I:=0 TO FILESIZE(ARCHIVOEVAL)-1 DO
  BEGIN
  SEEK(ARCHIVOEVAL, I);
  READ(ARCHIVOEVAL,X);
  IF X.NUM_LEGAJO = LEGAJO THEN
    BEGIN
    IF (X.FECHA_EVAL.DIA = (COPY(FECHA, 1, 2))) AND
       (X.FECHA_EVAL.MES = (COPY(FECHA, 4, 2))) AND
       (X.FECHA_EVAL.ANIO = (COPY(FECHA, 7, 4))) THEN
      BUSCAREVALUACION := I;
  END;
END;
END;

PROCEDURE CONSULTAEVALUACION(VAR RAIZLEGAJO: T_PUNT_ARBOL; VAR ARCHIVOEVAL: T_ARCHIVO_EVAL; VAR ARCHIVOALUMNO:T_ARCHIVO_ALUMNOS; POSALUMNO: INTEGER);
VAR
  BUSCADOLEGAJO: STRING;
  BUSCADOFECHA: STRING;
  POS: INTEGER;
  X: T_DATO_EVAL;
  Y:T_DATO_ALUMNOS;
  DIA,MES,ANIO:STRING;
BEGIN
  CLRSCR;
  GOTOXY(52,10);
  WRITELN('**CONSULTA EVALUACION**');
  TEXTCOLOR(GREEN);
  GOTOXY(45,12);

  SEEK(ARCHIVOALUMNO,POSALUMNO);
  READ(ARCHIVOALUMNO,Y);
  X.NUM_LEGAJO:= Y.NUM_LEGAJO;
  BUSCADOLEGAJO:=   X.NUM_LEGAJO;

  TEXTCOLOR(GREEN);
  GOTOXY(42,14);
  WRITE('INGRESE FECHA DE LA EVALUACION');
   TEXTCOLOR(GREEN);
  GOTOXY(45,16);
  WRITE('INGRESE EL DIA: ');
  TEXTCOLOR(WHITE);
  READLN(DIA);

  WHILE NOT VALIDARFECHADIAMES(DIA) DO
       BEGIN
       GOTOXY(55,16);
       WRITELN('                                                                                             ');
       GOTOXY(45,24);
       TEXTCOLOR(RED);
       WRITELN('DIA INVALIDO, POR FAVOR VERIFIQUE E INGRESE NUEVAMENTE');
       TEXTCOLOR(GREEN);
       GOTOXY(45,16);
       WRITE('INGRESE EL DIA: ');
       TEXTCOLOR(WHITE);
       READLN(DIA);
       GOTOXY(45,24);
       WRITELN('                                                                                             ');
       END;


  TEXTCOLOR(GREEN);
  GOTOXY(45,18);
  WRITE('INGRESE EL MES: ');
  TEXTCOLOR(WHITE);
  READLN(MES);

        WHILE NOT VALIDARFECHADIAMES(MES) DO
          BEGIN
          GOTOXY(55,18);
          WRITELN('                                                                                             ');
          GOTOXY(45,24);
          TEXTCOLOR(RED);
          WRITELN('MES INVALIDO, POR FAVOR VERIFIQUE E INGRESE NUEVAMENTE');
          TEXTCOLOR(GREEN);
          GOTOXY(45,18);
          WRITE('INGRESE EL MES: ');
          TEXTCOLOR(WHITE);
          READLN(MES);
          GOTOXY(45,24);
          WRITELN('                                                                                             ');
          END;


  TEXTCOLOR(GREEN);
  GOTOXY(45,20);
  WRITE('INGRESE EL AÑO: ');
  TEXTCOLOR(WHITE);
  READLN(ANIO);

      WHILE NOT VALIDARFECHAANIO(ANIO) DO
          BEGIN
          GOTOXY(55,20);
          WRITELN('                                                                                             ');
          GOTOXY(45,24);
          TEXTCOLOR(RED);
          WRITELN('AÑO INVALIDO, POR FAVOR VERIFIQUE E INGRESE NUEVAMENTE');
          TEXTCOLOR(GREEN);
          GOTOXY(45,20);
          WRITE('INGRESE EL AÑO: ');
          TEXTCOLOR(WHITE);
          READLN(ANIO);
          GOTOXY(45,24);
          WRITELN('                                                                                             ');
          END;


  BUSCADOFECHA := DIA + '/' + MES + '/' + ANIO;

  WHILE NOT  ESFECHAVALIDA(BUSCADOFECHA) DO
  BEGIN
       CLRSCR;
            TEXTCOLOR(RED);
        GOTOXY(45,11);
        WRITELN('FECHA INGRESADA NO VALIDA. POR FAVOR REVISE SUS DATOS');
        GOTOXY(42,12);
        WRITELN( 'RECUERDE DAR DIA, MES Y AÑO DE LA EVALUACION POR SEPARADO');
         TEXTCOLOR(GREEN);
        GOTOXY(45,14);
        WRITE('INGRESE FECHA DE LA EVALUACION: ');
         TEXTCOLOR(GREEN);
        GOTOXY(45,16);
        WRITE('INGRESE EL DIA: ');
        TEXTCOLOR(WHITE);
        READLN(DIA);
        TEXTCOLOR(GREEN);
        GOTOXY(45,18);
        WRITE('INGRESE EL MES: ');
        TEXTCOLOR(WHITE);
        READLN(MES);
        TEXTCOLOR(GREEN);
        GOTOXY(45,20);
        WRITE('INGRESE EL AÑO: ');
        TEXTCOLOR(WHITE);
        READLN(ANIO);
        BUSCADOFECHA := DIA + '/' + MES + '/' + ANIO;
  END;

  POS := BUSCAREVALUACION(RAIZLEGAJO, ARCHIVOEVAL, BUSCADOLEGAJO, BUSCADOFECHA);
  IF POS = -1 THEN
    BEGIN
      CLRSCR;
      TEXTCOLOR(RED);
      GOTOXY(41,14);
      WRITELN('NO SE ENCUENTRA REGISTRO DE EVALUACION');
      TEXTCOLOR(YELLOW);
      GOTOXY(45,16);
      WRITELN('OPRIMA <<ENTER>> PARA RECARGAR');
      READKEY;
    END
  ELSE
    BEGIN
      SEEK(ARCHIVOEVAL, POS);
      READ(ARCHIVOEVAL, X);
      MUESTRADATOSEVAL(X);
    END;
    READKEY;
    CLRSCR;
END;



PROCEDURE MODIFICAREVAL(VAR RAIZAPYNOM, RAIZLEGAJO: T_PUNT_ARBOL; VAR ARCHIVOEVAL: T_ARCHIVO_EVAL; VAR ARCHIVOALUMNO:T_ARCHIVO_ALUMNOS; POSALUMNO:INTEGER);
VAR
  LEGAJO, FECHA,OPCION: STRING;
  POS: INTEGER;
  X: T_DATO_EVAL;
  I: INTEGER;
  DIA,MES,ANIO:STRING;
  Y:T_DATO_ALUMNOS;
BEGIN
  CLRSCR;
  GOTOXY(50,10);
  WRITELN('**MODIFICAR EVALUACION**');
  TEXTCOLOR(GREEN);
  GOTOXY(45,12);

  SEEK(ARCHIVOALUMNO, POSALUMNO);
  READ(ARCHIVOALUMNO, Y);
  X.NUM_LEGAJO := Y.NUM_LEGAJO;

  TEXTCOLOR(GREEN);
  GOTOXY(45,14);
  WRITE('INGRESE EL DIA: ');
  TEXTCOLOR(WHITE);
  READLN(DIA);
     WHILE NOT VALIDARFECHADIAMES(DIA) DO
          BEGIN
          GOTOXY(55,14);
          WRITELN('                                                                                             ');
          GOTOXY(45,24);
          TEXTCOLOR(RED);
          WRITELN('DIA INVALIDO, POR FAVOR VERIFIQUE E INGRESE NUEVAMENTE');
          TEXTCOLOR(GREEN);
          GOTOXY(45,14);
          WRITE('INGRESE EL DIA: ');
          TEXTCOLOR(WHITE);
          READLN(DIA);
          GOTOXY(45,24);
          WRITELN('                                                                                             ');
          END;

  TEXTCOLOR(GREEN);
  GOTOXY(45,16);
  WRITE('INGRESE EL MES: ');
  TEXTCOLOR(WHITE);
  READLN(MES);
       WHILE NOT(VALIDARFECHADIAMES(MES)) DO
          BEGIN
          GOTOXY(55,16);
          WRITELN('                                                                                             ');
          GOTOXY(45,24);
          TEXTCOLOR(RED);
          WRITELN('MES INVALIDO, POR FAVOR VERIFIQUE E INGRESE NUEVAMENTE');
          TEXTCOLOR(GREEN);
          GOTOXY(45,16);
          WRITE('INGRESE EL MES: ');
          TEXTCOLOR(WHITE);
          READLN(MES);
          GOTOXY(45,24);
          WRITELN('                                                                                             ');
          END;



  TEXTCOLOR(GREEN);
  GOTOXY(45,18);
  WRITE('INGRESE EL AÑO: ');
  TEXTCOLOR(WHITE);
  READLN(ANIO);
      WHILE NOT(VALIDARFECHAANIO(ANIO)) DO
          BEGIN
          GOTOXY(55,18);
          WRITELN('                                                                                             ');
          GOTOXY(45,24);
          TEXTCOLOR(RED);
          WRITELN('AÑO INVALIDO, POR FAVOR VERIFIQUE E INGRESE NUEVAMENTE');
          TEXTCOLOR(GREEN);
          GOTOXY(45,18);
          WRITE('INGRESE EL AÑO: ');
          TEXTCOLOR(WHITE);
          READLN(ANIO);
          GOTOXY(45,24);
          WRITELN('                                                                                             ');
          END;


  FECHA := DIA + '/' + MES + '/' + ANIO;

  WHILE NOT  ESFECHAVALIDA(FECHA) DO
  BEGIN
       CLRSCR;
       TEXTCOLOR(RED);
        GOTOXY(45,11);
        WRITELN('FECHA INGRESADA NO VALIDA. POR FAVOR REVISE SUS DATOS');
        GOTOXY(42,12);
        WRITELN('RECUERDE DAR DIA, MES Y AÑO DE LA EVALUACION POR SEPARADO');
        TEXTCOLOR(GREEN);
        GOTOXY(45,14);
        WRITE('INGRESE DIA: ');
        TEXTCOLOR(WHITE);
        READLN(DIA);
        TEXTCOLOR(GREEN);
        GOTOXY(45,16);
        WRITE('INGRESE MES: ');
        TEXTCOLOR(WHITE);
        READLN(MES);
        TEXTCOLOR(GREEN);
        GOTOXY(45,18);
        WRITE('INGRESE AÑO: ');
        TEXTCOLOR(WHITE);
        READLN(ANIO);
        FECHA := DIA + '/' + MES + '/' + ANIO;

  END;
  POS := BUSCAREVALUACION(RAIZLEGAJO,ARCHIVOEVAL,X.NUM_LEGAJO,FECHA);
  IF POS = -1 THEN
    BEGIN
    CLRSCR;
    GOTOXY(45,16);
    TEXTCOLOR(RED);
    WRITELN('NO SE ENCUENTRA REGISTRO DE EVALUACION')
    END
  ELSE
    BEGIN
      SEEK(ARCHIVOEVAL, POS);
      READ(ARCHIVOEVAL, X);

      MUESTRADATOSEVAL(X);

      TEXTCOLOR(YELLOW);
      GOTOXY(55,10);
      WRITELN('INGRESE EL CAMPO A MODIFICAR DE LA EVALUACION:');
       TEXTCOLOR(GREEN);
      GOTOXY(55,12);
      WRITE('0- ');
      TEXTCOLOR(WHITE);
      WRITELN('VOLVER AL MENÚ DE SEGUIMIENTO');
      TEXTCOLOR(GREEN);
      GOTOXY(55,14);
      WRITE('1- ');
      TEXTCOLOR(WHITE);
      WRITELN('FECHA DE LA EVALUACION (DD/MM/AAAA)');
      TEXTCOLOR(GREEN);
      GOTOXY(55,16);
      WRITE('2- ');
      TEXTCOLOR(WHITE);
      WRITELN('VALORACION (1-5)');
      TEXTCOLOR(GREEN);
      GOTOXY(55,18);
      WRITE('3- ');
      TEXTCOLOR(WHITE);
      WRITELN('OBSERVACIONES');
      TEXTCOLOR(GREEN);
      GOTOXY(55,20);
      WRITE('OPCION: ');
      TEXTCOLOR(WHITE);
      READLN(OPCION);
      WHILE NOT ESNUMERO(OPCION) OR (OPCION < '0') OR (OPCION > '3') DO
       BEGIN
       GOTOXY(62,20);
       WRITE('                                                         ');
       TEXTCOLOR(GREEN);
       GOTOXY(55,20);
       WRITE('OPCION: ');
       TEXTCOLOR(WHITE);
       READLN(OPCION);
       END;

        CASE OPCION OF
          '1':
          BEGIN
            REPEAT
            CLRSCR;
            TEXTCOLOR(GREEN);
            GOTOXY(40,12);
            WRITE('INGRESE LA NUEVA FECHA DE LA EVALUACION (DD/MM/AAAA): ');
            TEXTCOLOR(GREEN);
             GOTOXY(45,14);
             WRITE('INGRESE DIA: ');
             TEXTCOLOR(WHITE);
             READLN(DIA);
             WHILE NOT(ESNUMERO(DIA)) OR (LENGTH(DIA) <> 2) DO
          BEGIN
         GOTOXY(45,24);
          TEXTCOLOR(RED);
          WRITELN('DIA INVALIDO, POR FAVOR VERIFIQUE E INGRESE NUEVAMENTE. EJ: 02');
          TEXTCOLOR(GREEN);
          GOTOXY(45,14);
          WRITE('INGRESE DIA: ');
          TEXTCOLOR(WHITE);
          READLN(DIA);
          GOTOXY(45,24);
          WRITELN('                                                                                             ');
          END;


             TEXTCOLOR(GREEN);
             GOTOXY(45,16);
             WRITE('INGRESE MES: ');
             TEXTCOLOR(WHITE);
             READLN(MES);
             WHILE NOT(ESNUMERO(MES)) OR (LENGTH(MES) <> 2) DO
          BEGIN
         GOTOXY(45,24);
          TEXTCOLOR(RED);
          WRITELN('MES INVALIDO, POR FAVOR VERIFIQUE E INGRESE NUEVAMENTE. EJ: 01');
          TEXTCOLOR(GREEN);
          GOTOXY(45,16);
          WRITE('INGRESE MES: ');
          TEXTCOLOR(WHITE);
          READLN(MES);
          GOTOXY(45,24);
          WRITELN('                                                                                             ');
          END;

             TEXTCOLOR(GREEN);
             GOTOXY(45,18);
             WRITE('INGRESE AÑO: ');
             TEXTCOLOR(WHITE);
             READLN(ANIO);
             WHILE NOT(ESNUMERO(ANIO)) OR (LENGTH(ANIO) <> 4) DO
          BEGIN
         GOTOXY(45,24);
          TEXTCOLOR(RED);
          WRITELN('AÑO INVALIDO, POR FAVOR VERIFIQUE E INGRESE NUEVAMENTE. EJ: 2025');
          TEXTCOLOR(GREEN);
          GOTOXY(45,18);
          WRITE('INGRESE AÑO: ');
          TEXTCOLOR(WHITE);
          READLN(ANIO);
          GOTOXY(45,24);
          WRITELN('                                                                                             ');
          END;

             FECHA := DIA + '/' + MES + '/' + ANIO;
           IF NOT ESFECHAVALIDA(FECHA) THEN
     BEGIN
       CLRSCR;
       TEXTCOLOR(RED);
       GOTOXY(30,15);
       WRITELN('FECHA INVALIDA. VUELVA A INGRESAR CORRECTAMENTE LOS DATOS');
       TEXTCOLOR(WHITE);
       GOTOXY(43,17);
       WRITELN('OPRIMA <<ENTER>> PARA RECARGAR');
       READKEY;
       CLRSCR;
     END
           ELSE
           X.FECHA_EVAL.DIA:=DIA;
           X.FECHA_EVAL.MES:=MES;
           X.FECHA_EVAL.ANIO:=ANIO;

    UNTIL ESFECHAVALIDA(FECHA);
          END;
          '2':
          BEGIN
           CLRSCR;
           MUESTRADATOSEVAL(X);
           TEXTCOLOR(GREEN);
           GOTOXY(50,11);
           WRITELN(' * INGRESE LA DISCAPACIDAD A MODIFICAR SU VALORACIÓN * ');
           TEXTCOLOR(WHITE);
           GOTOXY(50,13);
           WRITELN('1- PROBLEMAS DEL HABLA Y LENGUAJE');
           GOTOXY(50,14);
           WRITELN('2- DIFICULTAD PARA ESCRIBIR');
           GOTOXY(50,15);
           WRITELN('3- DIFICULTADES DE APRENDIZAJE VISUAL');
           GOTOXY(50,16);
           WRITELN('4- MEMORIA Y OTRAS DIFICULTADES DEL PENSAMIENTO');
           GOTOXY(50,17);
           WRITELN('5- DESTREZAS SOCIALES INADECUADAS');
           GOTOXY(50,19);
           TEXTCOLOR(GREEN);
           WRITE ('RESPUESTA: ');
           TEXTCOLOR(WHITE);
            READLN(I);

            GOTOXY(27,22);
            TEXTCOLOR(GREEN);
            WRITE('INGRESE LA NUEVA VALORACION (0-4) PARA ', OBTENERNOMBREDISCAPACIDAD(I), ': ');


              TEXTCOLOR(WHITE);
              IF X.VALORACION[I] = 0 THEN
                BEGIN
                CLRSCR;
                GOTOXY(27,22);
                 WRITELN('ALUMNO NO POSEE DICHA DISCAPACIDAD. NO SE PUEDE VALORAR NI MODIFICAR');
                 GOTOXY(27,24);
                 TEXTCOLOR(RED);
                 WRITELN('OPRIMA <<ENTER>> PARA REGRESAR AL MENU');
                 READKEY;
                 END
                 ELSE
              READLN(X.VALORACION[I]);
          END;
          '3':
          BEGIN
            CLRSCR;
            TEXTCOLOR(GREEN);
            GOTOXY(45,12);
            WRITE('INGRESE LAS NUEVAS OBSERVACIONES: ');
            TEXTCOLOR(WHITE);
            READLN(X.OBS);
          END;
        END;

        SEEK(ARCHIVOEVAL, POS);
        WRITE(ARCHIVOEVAL, X);
        PANTALLACARGA2;
        CLRSCR;
      END;
END;

PROCEDURE MUESTRA_REGISTRO_POR_TABLA_EVAL (VAR X: T_DATO_EVAL);
VAR
  FECHA:STRING;
BEGIN
  FECHA:=(X.FECHA_EVAL.DIA) + ' / ' + (X.FECHA_EVAL.MES) + ' / ' + (X.FECHA_EVAL.ANIO);
  WITH X DO
  BEGIN
    WRITE(NUM_LEGAJO:10, FECHA:30, VALORACION[1]:12, VALORACION[2]:10, VALORACION[3]:10, VALORACION[4]:10, VALORACION[5]:10);
    WRITELN;
  END;
END;


 END.