UNIT MENUESFINAL;

{$CODEPAGE UTF8}

INTERFACE

USES
  CRT, ARCHIVOALUM, ARCHIVOEVAL, UNITARBOL, MANEJOALUMNO, MANEJOEVAL, LISTADOS, ESTADISTICAS;

PROCEDURE MENUPRINCIAL ( );
PROCEDURE MENUESTADISTICAS (VAR ARCHIVOEVAL:T_ARCHIVO_EVAL; VAR ARCH:T_ARCHIVO_ALUMNOS);
PROCEDURE MENUALUMNO (var archivoAlumno:t_archivo_alumnos; var RAIZLEGAJO, RAIZAPYNOM:T_PUNT_ARBOL);
PROCEDURE MENUSEGUIMIENTO (var RAIZLEGAJO, RAIZFECHA:T_PUNT_ARBOL; var archivoEval:t_archivo_eval);
PROCEDURE MENULISTADOS (VAR ARCH:T_ARCHIVO_ALUMNOS; RAIZAPYNOM, RAIZLEGAJO:T_PUNT_ARBOL; var ARCH2:T_ARCHIVO_EVAL);

IMPLEMENTATION

PROCEDURE MENUALUMNO (var archivoAlumno:t_archivo_alumnos; var RAIZLEGAJO, RAIZAPYNOM:T_PUNT_ARBOL);
VAR
  OPCION:0..4;
  x:t_dato_alumnos;
BEGIN
  CLRSCR;
  TEXTCOLOR(WHITE);
  GOTOXY(50,10);
  WRITE('**BIENVENIDO AL ');
  TEXTCOLOR(GREEN);
  WRITELN('MENU DE ALUMNO**');
  REPEAT
       TEXTCOLOR(GREEN);
       GOTOXY(52,12);
       WRITE('0- ');
       TEXTCOLOR(WHITE);
       WRITELN('VOLVER AL MENU PRINCIPAL');
       TEXTCOLOR(GREEN);
       GOTOXY(52,14);
       WRITE('1- ');
       TEXTCOLOR(WHITE);
       WRITELN('ALTA');
       TEXTCOLOR(GREEN);
       GOTOXY(52,16);
       WRITE('2- ');
       TEXTCOLOR(WHITE);
       WRITELN('BAJA');
       TEXTCOLOR(GREEN);
       GOTOXY(52,18);
       WRITE('3- ');
       TEXTCOLOR(WHITE);
       WRITELN('MODIFICACIÓN');
       TEXTCOLOR(GREEN);
       GOTOXY(52,20);
       WRITE('4- ');
       TEXTCOLOR(WHITE);
       WRITELN('CONSULTA');
       TEXTCOLOR(GREEN);
       GOTOXY(52,22);
       WRITE('RESPUESTA: ');
       TEXTCOLOR(WHITE);
       READLN(OPCION);
       CASE OPCION OF
            1:DarAltaAlumno (archivoAlumno,x);
            2:BajaAlumno(raizapynom,raizlegajo,archivoAlumno);
            3:ModificarAlumno(raizapynom, raizlegajo,archivoAlumno);
            4:ConsultaAlumnos(raizapynom, raizlegajo,archivoAlumno);
       END;
  UNTIL OPCION = 0 ;
  CLRSCR;
END;

PROCEDURE MENUSEGUIMIENTO (var RAIZLEGAJO, RAIZFECHA:T_PUNT_ARBOL; var archivoEval:t_archivo_eval);
VAR
  OPCION:0..3;
  x:t_dato_eval;
BEGIN
  CLRSCR;
  PASAR_DATOS_EVAL (archivoEval,RAIZLEGAJO,RAIZFECHA);
  TEXTCOLOR(WHITE);
  GOTOXY(48,10);
  WRITE('**BIENVENIDO AL ');
  TEXTCOLOR(GREEN);
  WRITELN('MENU DE SEGUIMIENTO**');
  REPEAT
       TEXTCOLOR(GREEN);
       GOTOXY(52,12);
       WRITE('0- ');
       TEXTCOLOR(WHITE);
       WRITELN('VOLVER AL MENU PRINCIPAL');
       TEXTCOLOR(GREEN);
       GOTOXY(52,14);
       WRITE('1- ');
       TEXTCOLOR(WHITE);
       WRITELN('ALTA');
       TEXTCOLOR(GREEN);
       GOTOXY(52,16);
       WRITE('2- ');
       TEXTCOLOR(WHITE);
       WRITELN('MODIFICACIÓN');
       TEXTCOLOR(GREEN);
       GOTOXY(52,18);
       WRITE('3- ');
       TEXTCOLOR(WHITE);
       WRITELN('CONSULTA');
       TEXTCOLOR(GREEN);
       GOTOXY(52,20);
       WRITE('RESPUESTA: ');
       TEXTCOLOR(WHITE);
       READLN(OPCION);
       CASE OPCION OF
            1:DarAltaEval(archivoEval,x);
            2:modificarEval(raizfecha, raizlegajo,archivoEval);
            3:ConsultaEvaluacion(raizlegajo,archivoEval);
       END;
  UNTIL OPCION = 0 ;
  CLRSCR;
END;

PROCEDURE MENULISTADOS (VAR ARCH:T_ARCHIVO_ALUMNOS; RAIZAPYNOM, RAIZLEGAJO:T_PUNT_ARBOL; var ARCH2:T_ARCHIVO_EVAL);
VAR
  OPCION:0..3;
BEGIN
  CLRSCR;
  TEXTCOLOR(WHITE);
  GOTOXY(49,10);
  WRITE('**BIENVENIDO AL ');
  TEXTCOLOR(GREEN);
  WRITELN('MENU DE LISTADOS**');
  REPEAT
       TEXTCOLOR(GREEN);
       GOTOXY(52,12);
       WRITE('0- ');
       TEXTCOLOR(WHITE);
       WRITELN('VOLVER AL MENU PRINCIPAL');
       TEXTCOLOR(GREEN);
       GOTOXY(52,14);
       WRITE('1- ');
       TEXTCOLOR(WHITE);
       WRITELN('NOMBRE Y APELLIDO');
       TEXTCOLOR(GREEN);
       GOTOXY(52,16);
       WRITE('2- ');
       TEXTCOLOR(WHITE);
       WRITELN('EVALUCIONES DE UN ALUMNO');
       TEXTCOLOR(GREEN);
       GOTOXY(52,18);
       WRITE('3- ');
       TEXTCOLOR(WHITE);
       WRITELN('ALUMNOS CON DETERMINADA DISCAPACIDAD');
       TEXTCOLOR(GREEN);
       GOTOXY(52,20);
       WRITE('RESPUESTA: ');
       TEXTCOLOR(WHITE);
       READLN(OPCION);
       CASE OPCION OF
            1: listado_apynom (ARCH, RAIZAPYNOM);
            2: ConsultaEvalDeAlumno(ARCH2,RAIZLEGAJO, RAIZAPYNOM);
            3:listado_por_enfermedad (ARCH);
       END;
  UNTIL OPCION = 0 ;
  CLRSCR;
END;

PROCEDURE MENUESTADISTICAS (VAR ARCHIVOEVAL:T_ARCHIVO_EVAL; VAR ARCH:T_ARCHIVO_ALUMNOS);
VAR
   OPCION:0..4;
BEGIN
  CLRSCR;
  TEXTCOLOR(WHITE);
  GOTOXY(52,10);
  WRITE('**BIENVENIDO AL ');
  TEXTCOLOR(GREEN);
  WRITELN('MENU DE ESTADISTICAS**');
  REPEAT
       TEXTCOLOR(GREEN);
       GOTOXY(45,12);
       WRITE('0- ');
       TEXTCOLOR(WHITE);
       WRITELN('VOLVER AL MENU PRINCIPAL');
       TEXTCOLOR(GREEN);
       GOTOXY(45,14);
       WRITE('1- ');
       TEXTCOLOR(WHITE);
       WRITELN('DISTRIBUCIÓN DE EVALUACIONES POR DISCAPACIDAD');
       TEXTCOLOR(GREEN);
       GOTOXY(45,16);
       WRITE('2- ');
       TEXTCOLOR(WHITE);
       WRITELN('DISCAPACIDAD QUE PRESENTAN MAYOR GRADO DE DIFICULTAD');
       TEXTCOLOR(GREEN);
       GOTOXY(45,18);
       WRITE('3- ');
       TEXTCOLOR(WHITE);
       WRITELN('CANTIDAD DE ALUMNOS POR UNA DETERMINADA DISCAPACIDAD');
       TEXTCOLOR(GREEN);
       GOTOXY(45,20);
       WRITE('RESPUESTA: ');
       TEXTCOLOR(WHITE);
       READLN(OPCION);
       CASE OPCION OF
            1:evaluacionesPorFecha(ARCHIVOEVAL);
            2:compararValoracionesPorFecha(ARCHIVOEVAL);
            3:MUESTRADISCAPACIDADES (ARCH);
       END;
  UNTIL OPCION = 0 ;
  CLRSCR;
END;

PROCEDURE MENUPRINCIAL ();
VAR
  OPCION:0..4;
  ARCH:T_ARCHIVO_ALUMNOS;
  ARCH2:T_ARCHIVO_EVAL;
  RAIZ,RAIZ2:T_PUNT_ARBOL ;
BEGIN
      CREAR_ABRIR (ARCH);
      CREAR_ABRIR2 (ARCH2);
      CREAR_ARBOL ( RAIZ);
      CREAR_ARBOL ( RAIZ2);
      PASAR_DATOS (ARCH,RAIZ,RAIZ2);
     TEXTCOLOR(WHITE);
     GOTOXY(40,10);
     WRITE('**BIENVENIDO A ');
     TEXTCOLOR(GREEN);
     WRITELN('SEGUIMIENTO DE APRENDIZAJE**');
  REPEAT
       TEXTCOLOR(GREEN);
       GOTOXY(52,12);
       WRITE('1- ');
       TEXTCOLOR(WHITE);
       WRITELN('ALUMNO');
       GOTOXY(52,14);
       TEXTCOLOR(GREEN);
       WRITE('2- ');
       TEXTCOLOR(WHITE);
       WRITELN('SEGUIMIENTO');
       GOTOXY(52,16);
       TEXTCOLOR(GREEN);
       WRITE('3- ');
       TEXTCOLOR(WHITE);
       WRITELN('LISTADOS');
       GOTOXY(52,18);
       TEXTCOLOR(GREEN);
       WRITE('4- ');
       TEXTCOLOR(WHITE);
       WRITELN('ESTADISTICAS');
       GOTOXY(52,20);
       TEXTCOLOR(GREEN);
       WRITE('RESPUESTA: ');
       TEXTCOLOR(WHITE);
       READLN(OPCION);
         CASE OPCION OF
            1:MENUALUMNO (arch,RAIZ, RAIZ2);
            2:MENUSEGUIMIENTO (RAIZ, RAIZ2,ARCH2);
            3:MENULISTADOS (ARCH,RAIZ,RAIZ2,ARCH2);
            4:MENUESTADISTICAS (arch2, ARCH);
       END;
  UNTIL OPCION = 0 ;
  CERRAR(ARCH);
  CERRAR2(ARCH2);
END;



END.